# Generated by Django 5.1.7 on 2025-03-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0002_user_driver_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_transito', 'Em Trânsito'), ('concluida', 'Concluída')], default='pendente', max_length=32),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
