# Generated by Django 5.1.7 on 2025-04-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0004_order_last_update_alter_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='user_name',
        ),
        migrations.AddField(
            model_name='driver',
            name='password',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='username',
            field=models.CharField(default=0, max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
