# Generated by Django 5.1.7 on 2025-04-02 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
        ('order_manager', '0005_delete_user_remove_driver_user_name_driver_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='driver.driver'),
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
