# Generated by Django 5.1.7 on 2025-04-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_alter_driver_options_alter_driver_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
