# Generated by Django 5.1.7 on 2025-04-03 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0005_user'),
        ('order_manager', '0007_alter_order_driver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
